image:
  file: .gitpod.Dockerfile
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install nodemon
    command: npm i -g nodemon && npm start
  - name: getting port
  - command: python3 -m http.server 8000
  - name: preview
  - command: gp preview $(gp url 8000)