image:
  file: .gitpod.Dockerfile
   FROM gitpod/workspace-full
tasks:
  - name: Running MongoDB
    command: mkdir -p data && mongod --dbpath data
  - name: Install nodemon
    command: npm i -g nodemon && npm start


ports:
  - port: 3000
    onOpen: open-preview 
 
